# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bukkakegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bukkake',
            name='created_date',
        ),
    ]
