# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bukkakegram', '0002_remove_bukkake_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukkake',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
