# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukkakegram', '0003_bukkake_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukkake',
            name='description',
            field=models.TextField(default='lorem ipsum'),
            preserve_default=False,
        ),
    ]
