# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukkake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukkake',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
