# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukkake', '0002_bukkake_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukkake',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
