# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukkake', '0003_bukkake_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukkake',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
