# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bukkake', '0005_bukkake_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukkake',
            name='filters',
            field=models.CharField(choices=[('no', 'normal'), ('cl', 'clarendon'), ('gi', 'gingham'), ('mo', 'moon'), ('la', 'lark'), ('re', 'reyes'), ('ju', 'juno'), ('sl', 'slumber'), ('ad', 'aden'), ('pe', 'perpetua'), ('ma', 'mayfair'), ('ri', 'rise'), ('hu', 'hudson')], default='cl', max_length=2),
        ),
    ]
